---
# https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/

- include_vars: "{{ ansible_os_family | lower }}.yml"
  name: Include OS specific vars

- include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'
  name: Install NGINX on Rocky

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
  name: Install NGINX on Debian

- include_tasks: post-install.yml
  name: Set index.html content