---
- name: Customize index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_index_html_location }}/index.html"

- name: Make sure nginx is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
