---
driver:
  name: docker
platforms:
  - name: rocky
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    published_ports:
      - 8080:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian
    image: geerlingguy/docker-debian12-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    published_ports:
      - 8081:80
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}