---
- name: Verify
  hosts: all
  vars:
    expected_content: "NGINX is running on {{ansible_distribution}} {{ ansible_distribution_version }} ({{ansible_distribution_release}})"
  tasks:
  - name: Get index.html
    ansible.builtin.uri:
      url: http://localhost
      return_content: yes
    register: this
    failed_when: "expected_content not in this.content"
