---
name: CI
on: workflow_dispatch
jobs:
  yamllint:
    name: YAML linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

  ansible-lint:
    name: Ansible linting
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c .ansible-lint"
